// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/list-companies.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (ou VITE_SUPABASE_URL) \xE9 obrigat\xF3rio");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS ou SUPABASE_ANON_KEY \xE9 obrigat\xF3rio");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser exige um token OAuth verificado");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "N\xE3o autenticado. Conecte-se novamente ao Aveto 360." }],
    isError: true
  };
}

// src/lib/mcp/tools/list-companies.ts
var list_companies_default = defineTool({
  name: "list_companies",
  title: "Listar empresas",
  description: "Lista as empresas (perfis PJ) que o usu\xE1rio conectado pode acessar no Aveto 360.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("companies").select("id, name, trade_name, cnpj, is_active, profile_type, cidade, uf").order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { companies: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-accounts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^3.23.8";
var list_accounts_default = defineTool2({
  name: "list_accounts",
  title: "Listar contas e saldos",
  description: "Lista as contas banc\xE1rias/caixa com o saldo atual. Opcionalmente filtra por empresa (company_id) ou contexto PF/PJ.",
  inputSchema: {
    company_id: z.string().uuid().optional().describe("Filtra pelas contas de uma empresa (PJ)."),
    context: z.enum(["pf", "pj"]).optional().describe("Contexto: pessoal (pf) ou empresarial (pj).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ company_id, context }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("accounts").select("id, name, account_type, context, company_id, current_balance, is_active, bank_slug").is("soft_deleted_at", null).order("name");
    if (company_id) query = query.eq("company_id", company_id);
    if (context) query = query.eq("context", context);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const total = rows.reduce((sum, r) => sum + Number(r.current_balance ?? 0), 0);
    return {
      content: [{ type: "text", text: JSON.stringify({ total_balance: total, accounts: rows }, null, 2) }],
      structuredContent: { total_balance: total, accounts: rows }
    };
  }
});

// src/lib/mcp/tools/list-transactions.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^3.23.8";
var DATE = z2.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Use o formato AAAA-MM-DD");
var list_transactions_default = defineTool3({
  name: "list_transactions",
  title: "Listar lan\xE7amentos",
  description: "Lista lan\xE7amentos financeiros (entradas, sa\xEDdas, contas a pagar/receber) com filtros de per\xEDodo, empresa, tipo e situa\xE7\xE3o.",
  inputSchema: {
    company_id: z2.string().uuid().optional().describe("Filtra por empresa (PJ)."),
    context: z2.enum(["pf", "pj"]).optional().describe("Contexto: pessoal (pf) ou empresarial (pj)."),
    start_date: DATE.optional().describe("Data inicial (transaction_date)."),
    end_date: DATE.optional().describe("Data final (transaction_date)."),
    transaction_type: z2.enum(["entrada", "saida", "transferencia", "parcelado"]).optional().describe("Tipo do lan\xE7amento."),
    status: z2.enum(["pendente", "confirmado", "cancelado"]).optional().describe("Situa\xE7\xE3o do lan\xE7amento."),
    limit: z2.number().int().min(1).max(200).default(50).describe("M\xE1ximo de registros (1-200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ company_id, context, start_date, end_date, transaction_type, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("transactions").select(
      "id, description, amount, amount_paid, transaction_date, due_date, payment_date, transaction_type, status, bill_status, context, company_id, category_id, account_id, counterparty_name"
    ).is("canceled_at", null).order("transaction_date", { ascending: false }).limit(limit ?? 50);
    if (company_id) query = query.eq("company_id", company_id);
    if (context) query = query.eq("context", context);
    if (start_date) query = query.gte("transaction_date", start_date);
    if (end_date) query = query.lte("transaction_date", end_date);
    if (transaction_type) query = query.eq("transaction_type", transaction_type);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const entradas = rows.filter((r) => r.transaction_type === "entrada").reduce((s, r) => s + Number(r.amount ?? 0), 0);
    const saidas = rows.filter((r) => r.transaction_type === "saida").reduce((s, r) => s + Number(r.amount ?? 0), 0);
    const payload = { count: rows.length, total_entradas: entradas, total_saidas: saidas, transactions: rows };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-colaboradores.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^3.23.8";
var list_colaboradores_default = defineTool4({
  name: "list_colaboradores",
  title: "Listar colaboradores (Pessoas 360\xB0)",
  description: "Lista os colaboradores de uma empresa no m\xF3dulo Pessoas 360\xB0, com cargo, unidade, v\xEDnculo e situa\xE7\xE3o.",
  inputSchema: {
    company_id: z3.string().uuid().describe("Empresa (PJ) dos colaboradores."),
    apenas_ativos: z3.boolean().default(true).describe("Quando verdadeiro, retorna somente colaboradores ativos."),
    limit: z3.number().int().min(1).max(200).default(100).describe("M\xE1ximo de registros (1-200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ company_id, apenas_ativos, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("dp_colaboradores").select(
      "id, nome, matricula, cargo, regime, vinculo_label, unidade_id, ativo, data_admissao, data_desligamento, perfil_acesso"
    ).eq("company_id", company_id).is("deleted_at", null).order("nome").limit(limit ?? 100);
    if (apenas_ativos !== false) query = query.eq("ativo", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ count: data?.length ?? 0, colaboradores: data ?? [] }, null, 2) }],
      structuredContent: { count: data?.length ?? 0, colaboradores: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "grtxmbffgmgnkawlvqhm";
var mcp_default = defineMcp({
  name: "360-food",
  title: "Aveto 360",
  version: "0.1.0",
  instructions: "Ferramentas do Aveto 360 (gest\xE3o financeira e de pessoas para food service). Use list_companies para descobrir as empresas do usu\xE1rio, list_accounts para saldos, list_transactions para lan\xE7amentos e contas a pagar/receber, e list_colaboradores para a equipe do m\xF3dulo Pessoas 360\xB0. Todas as chamadas respeitam as permiss\xF5es do usu\xE1rio conectado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_companies_default, list_accounts_default, list_transactions_default, list_colaboradores_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
