-- ============================================================
-- Fase 1.1 — Índices em FKs sem cobertura
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_budgets_category_id ON public.budgets (category_id);
CREATE INDEX IF NOT EXISTS idx_categories_company_id ON public.categories (company_id);
CREATE INDEX IF NOT EXISTS idx_categorization_rules_payment_method_id ON public.categorization_rules (payment_method_id);
CREATE INDEX IF NOT EXISTS idx_categorization_rules_category_id ON public.categorization_rules (category_id);
CREATE INDEX IF NOT EXISTS idx_category_templates_parent_code ON public.category_templates (parent_code);
CREATE INDEX IF NOT EXISTS idx_companies_segmento_id ON public.companies (segmento_id);
CREATE INDEX IF NOT EXISTS idx_coupon_redemptions_invoice_id ON public.coupon_redemptions (invoice_id);
CREATE INDEX IF NOT EXISTS idx_coupon_redemptions_subscription_id ON public.coupon_redemptions (subscription_id);
CREATE INDEX IF NOT EXISTS idx_credit_card_invoices_company_id ON public.credit_card_invoices (company_id);
CREATE INDEX IF NOT EXISTS idx_credit_card_invoices_payment_transaction_id ON public.credit_card_invoices (payment_transaction_id);
CREATE INDEX IF NOT EXISTS idx_credit_card_invoices_user_id ON public.credit_card_invoices (user_id);
CREATE INDEX IF NOT EXISTS idx_credit_cards_default_payment_account_id ON public.credit_cards (default_payment_account_id);
CREATE INDEX IF NOT EXISTS idx_credit_cards_cost_center_id ON public.credit_cards (cost_center_id);
CREATE INDEX IF NOT EXISTS idx_dp_avisos_colaborador_id ON public.dp_avisos (colaborador_id);
CREATE INDEX IF NOT EXISTS idx_dp_avisos_autor_id ON public.dp_avisos (autor_id);
CREATE INDEX IF NOT EXISTS idx_dp_avisos_unidade_id ON public.dp_avisos (unidade_id);
CREATE INDEX IF NOT EXISTS idx_dp_avisos_cargo_id ON public.dp_avisos (cargo_id);
CREATE INDEX IF NOT EXISTS idx_dp_avisos_comentarios_user_id ON public.dp_avisos_comentarios (user_id);
CREATE INDEX IF NOT EXISTS idx_dp_avisos_comentarios_colaborador_id ON public.dp_avisos_comentarios (colaborador_id);
CREATE INDEX IF NOT EXISTS idx_dp_avisos_comentarios_company_id ON public.dp_avisos_comentarios (company_id);
CREATE INDEX IF NOT EXISTS idx_dp_avisos_comentarios_moderado_por ON public.dp_avisos_comentarios (moderado_por);
CREATE INDEX IF NOT EXISTS idx_dp_avisos_leituras_user_id ON public.dp_avisos_leituras (user_id);
CREATE INDEX IF NOT EXISTS idx_dp_avisos_reacoes_user_id ON public.dp_avisos_reacoes (user_id);
CREATE INDEX IF NOT EXISTS idx_dp_bloqueio_regra_unidades_unidade_id ON public.dp_bloqueio_regra_unidades (unidade_id);
CREATE INDEX IF NOT EXISTS idx_dp_bloqueio_regras_criado_por ON public.dp_bloqueio_regras (criado_por);
CREATE INDEX IF NOT EXISTS idx_dp_bloqueios_criado_por ON public.dp_bloqueios (criado_por);
CREATE INDEX IF NOT EXISTS idx_dp_bulk_import_batches_uploaded_by ON public.dp_bulk_import_batches (uploaded_by);
CREATE INDEX IF NOT EXISTS idx_dp_bulk_import_items_imported_documento_id ON public.dp_bulk_import_items (imported_documento_id);
CREATE INDEX IF NOT EXISTS idx_dp_bulk_import_items_matched_colaborador_id ON public.dp_bulk_import_items (matched_colaborador_id);
CREATE INDEX IF NOT EXISTS idx_dp_bulk_import_items_company_id ON public.dp_bulk_import_items (company_id);
CREATE INDEX IF NOT EXISTS idx_dp_bulk_import_items_decided_by ON public.dp_bulk_import_items (decided_by);
CREATE INDEX IF NOT EXISTS idx_dp_bulk_import_items_duplicate_of ON public.dp_bulk_import_items (duplicate_of);
CREATE INDEX IF NOT EXISTS idx_dp_cadastro_solicitacoes_reviewed_by ON public.dp_cadastro_solicitacoes (reviewed_by);
CREATE INDEX IF NOT EXISTS idx_dp_cobertura_minima_unidade_id ON public.dp_cobertura_minima (unidade_id);
CREATE INDEX IF NOT EXISTS idx_dp_cobertura_minima_cargo_id ON public.dp_cobertura_minima (cargo_id);
CREATE INDEX IF NOT EXISTS idx_dp_cobertura_minima_turno_id ON public.dp_cobertura_minima (turno_id);
CREATE INDEX IF NOT EXISTS idx_dp_colaborador_beneficios_beneficio_id ON public.dp_colaborador_beneficios (beneficio_id);
CREATE INDEX IF NOT EXISTS idx_dp_colaborador_config_dias_company_id ON public.dp_colaborador_config_dias (company_id);
CREATE INDEX IF NOT EXISTS idx_dp_colaborador_config_dias_turno_id ON public.dp_colaborador_config_dias (turno_id);
CREATE INDEX IF NOT EXISTS idx_dp_colaborador_config_trabalho_turno_padrao_id ON public.dp_colaborador_config_trabalho (turno_padrao_id);
CREATE INDEX IF NOT EXISTS idx_dp_colaborador_jornadas_jornada_id ON public.dp_colaborador_jornadas (jornada_id);
CREATE INDEX IF NOT EXISTS idx_dp_colaboradores_sindicato_id ON public.dp_colaboradores (sindicato_id);
CREATE INDEX IF NOT EXISTS idx_dp_config_dp_negociacao_id ON public.dp_config_dp (negociacao_id);
CREATE INDEX IF NOT EXISTS idx_dp_config_dp_unidade_id ON public.dp_config_dp (unidade_id);
CREATE INDEX IF NOT EXISTS idx_dp_convocacoes_unidade_id ON public.dp_convocacoes (unidade_id);
CREATE INDEX IF NOT EXISTS idx_dp_convocacoes_turno_id ON public.dp_convocacoes (turno_id);
CREATE INDEX IF NOT EXISTS idx_dp_convocacoes_escala_item_id ON public.dp_convocacoes (escala_item_id);
CREATE INDEX IF NOT EXISTS idx_dp_datas_bloqueadas_criado_por ON public.dp_datas_bloqueadas (criado_por);
CREATE INDEX IF NOT EXISTS idx_dp_datas_bloqueadas_unidade_id ON public.dp_datas_bloqueadas (unidade_id);
CREATE INDEX IF NOT EXISTS idx_dp_datas_bloqueadas_regra_id ON public.dp_datas_bloqueadas (regra_id);
CREATE INDEX IF NOT EXISTS idx_dp_datas_bloqueadas_liberada_por_solicitacao ON public.dp_datas_bloqueadas (liberada_por_solicitacao);
CREATE INDEX IF NOT EXISTS idx_dp_dia_config_criado_por ON public.dp_dia_config (criado_por);
CREATE INDEX IF NOT EXISTS idx_dp_dia_config_unidade_id ON public.dp_dia_config (unidade_id);
CREATE INDEX IF NOT EXISTS idx_dp_documentos_uploaded_by ON public.dp_documentos (uploaded_by);
CREATE INDEX IF NOT EXISTS idx_dp_epis_entregas_colaborador_id ON public.dp_epis_entregas (colaborador_id);
CREATE INDEX IF NOT EXISTS idx_dp_epis_entregas_epi_id ON public.dp_epis_entregas (epi_id);
CREATE INDEX IF NOT EXISTS idx_dp_escala_itens_turno_id ON public.dp_escala_itens (turno_id);
CREATE INDEX IF NOT EXISTS idx_dp_escala_itens_colaborador_id ON public.dp_escala_itens (colaborador_id);
CREATE INDEX IF NOT EXISTS idx_dp_escalas_unidade_id ON public.dp_escalas (unidade_id);
CREATE INDEX IF NOT EXISTS idx_dp_exames_aso_colaborador_id ON public.dp_exames_aso (colaborador_id);
CREATE INDEX IF NOT EXISTS idx_dp_ferias_bloqueios_unidade_id ON public.dp_ferias_bloqueios (unidade_id);
CREATE INDEX IF NOT EXISTS idx_dp_ferias_gozos_colaborador_id ON public.dp_ferias_gozos (colaborador_id);
CREATE INDEX IF NOT EXISTS idx_dp_ferias_regras_cargo_id ON public.dp_ferias_regras (cargo_id);
CREATE INDEX IF NOT EXISTS idx_dp_ferias_regras_unidade_id ON public.dp_ferias_regras (unidade_id);
CREATE INDEX IF NOT EXISTS idx_dp_folgas_criado_por ON public.dp_folgas (criado_por);
CREATE INDEX IF NOT EXISTS idx_dp_folgas_canceladas_folga_id ON public.dp_folgas_canceladas (folga_id);
CREATE INDEX IF NOT EXISTS idx_dp_folgas_canceladas_cancelado_por ON public.dp_folgas_canceladas (cancelado_por);
CREATE INDEX IF NOT EXISTS idx_dp_folha_lancamentos_contracheque_documento_id ON public.dp_folha_lancamentos (contracheque_documento_id);
CREATE INDEX IF NOT EXISTS idx_dp_folha_lancamentos_financeiro_categoria_id ON public.dp_folha_lancamentos (financeiro_categoria_id);
CREATE INDEX IF NOT EXISTS idx_dp_folha_lancamentos_financeiro_account_id ON public.dp_folha_lancamentos (financeiro_account_id);
CREATE INDEX IF NOT EXISTS idx_dp_folha_lancamentos_transaction_id ON public.dp_folha_lancamentos (transaction_id);
CREATE INDEX IF NOT EXISTS idx_dp_legacy_import_runs_company_id ON public.dp_legacy_import_runs (company_id);
CREATE INDEX IF NOT EXISTS idx_dp_mensagens_remetente_id ON public.dp_mensagens (remetente_id);
CREATE INDEX IF NOT EXISTS idx_dp_mensagens_destinatario_user_id ON public.dp_mensagens (destinatario_user_id);
CREATE INDEX IF NOT EXISTS idx_dp_mensagens_destinatario_colaborador_id ON public.dp_mensagens (destinatario_colaborador_id);
CREATE INDEX IF NOT EXISTS idx_dp_modelos_mensagem_company_id ON public.dp_modelos_mensagem (company_id);
CREATE INDEX IF NOT EXISTS idx_dp_notificacoes_colaborador_id ON public.dp_notificacoes (colaborador_id);
CREATE INDEX IF NOT EXISTS idx_dp_pontos_unidade_id ON public.dp_pontos (unidade_id);
CREATE INDEX IF NOT EXISTS idx_dp_prioridade_aniversario_colaborador_id ON public.dp_prioridade_aniversario (colaborador_id);
CREATE INDEX IF NOT EXISTS idx_dp_registros_disciplinares_aplicado_por ON public.dp_registros_disciplinares (aplicado_por);
CREATE INDEX IF NOT EXISTS idx_dp_sindicato_cargos_cargo_id ON public.dp_sindicato_cargos (cargo_id);
CREATE INDEX IF NOT EXISTS idx_dp_sindicato_negociacoes_sindicato_laboral_id ON public.dp_sindicato_negociacoes (sindicato_laboral_id);
CREATE INDEX IF NOT EXISTS idx_dp_sindicato_negociacoes_unidade_id ON public.dp_sindicato_negociacoes (unidade_id);
CREATE INDEX IF NOT EXISTS idx_dp_sindicato_negociacoes_created_by ON public.dp_sindicato_negociacoes (created_by);
CREATE INDEX IF NOT EXISTS idx_dp_sindicato_unidades_unidade_id ON public.dp_sindicato_unidades (unidade_id);
CREATE INDEX IF NOT EXISTS idx_dp_solicitacoes_respondido_por ON public.dp_solicitacoes (respondido_por);
CREATE INDEX IF NOT EXISTS idx_dp_solicitacoes_criado_por ON public.dp_solicitacoes (criado_por);
CREATE INDEX IF NOT EXISTS idx_dp_treinamentos_participacoes_colaborador_id ON public.dp_treinamentos_participacoes (colaborador_id);
CREATE INDEX IF NOT EXISTS idx_dp_treinamentos_participacoes_treinamento_id ON public.dp_treinamentos_participacoes (treinamento_id);
CREATE INDEX IF NOT EXISTS idx_dp_trocas_destino_id ON public.dp_trocas (destino_id);
CREATE INDEX IF NOT EXISTS idx_dp_trocas_solicitante_id ON public.dp_trocas (solicitante_id);
CREATE INDEX IF NOT EXISTS idx_dp_trocas_gestor_id ON public.dp_trocas (gestor_id);
CREATE INDEX IF NOT EXISTS idx_dp_trocas_created_by ON public.dp_trocas (created_by);
CREATE INDEX IF NOT EXISTS idx_dp_turnos_unidade_id ON public.dp_turnos (unidade_id);
CREATE INDEX IF NOT EXISTS idx_dp_turnos_turno_origem_id ON public.dp_turnos (turno_origem_id);
CREATE INDEX IF NOT EXISTS idx_dp_unidade_cargos_cargo_id ON public.dp_unidade_cargos (cargo_id);
CREATE INDEX IF NOT EXISTS idx_import_rules_contact_id ON public.import_rules (contact_id);
CREATE INDEX IF NOT EXISTS idx_import_rules_company_id ON public.import_rules (company_id);
CREATE INDEX IF NOT EXISTS idx_import_rules_category_id ON public.import_rules (category_id);
CREATE INDEX IF NOT EXISTS idx_pluggy_accounts_linked_account_id ON public.pluggy_accounts (linked_account_id);
CREATE INDEX IF NOT EXISTS idx_pluggy_connections_created_by ON public.pluggy_connections (created_by);
CREATE INDEX IF NOT EXISTS idx_pluggy_staging_transactions_suggested_account_id ON public.pluggy_staging_transactions (suggested_account_id);
CREATE INDEX IF NOT EXISTS idx_pluggy_staging_transactions_suggested_category_id ON public.pluggy_staging_transactions (suggested_category_id);
CREATE INDEX IF NOT EXISTS idx_pluggy_staging_transactions_matched_transaction_id ON public.pluggy_staging_transactions (matched_transaction_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_plan_id ON public.subscriptions (plan_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_exempted_by ON public.subscriptions (exempted_by);
CREATE INDEX IF NOT EXISTS idx_transactions_superseded_by_transaction_id ON public.transactions (superseded_by_transaction_id);

-- ============================================================
-- Fase 1.1b — Índices compostos nos caminhos quentes por tenant
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_transactions_company_due ON public.transactions (company_id, due_date) WHERE company_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_transactions_user_ctx_due ON public.transactions (user_id, context, due_date);
CREATE INDEX IF NOT EXISTS idx_transactions_company_status_due ON public.transactions (company_id, status, due_date) WHERE company_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_dp_pontos_colab_data ON public.dp_pontos (colaborador_id, data);
CREATE INDEX IF NOT EXISTS idx_dp_escala_itens_company_data ON public.dp_escala_itens (company_id, data);
CREATE INDEX IF NOT EXISTS idx_dp_escala_itens_colab_data ON public.dp_escala_itens (colaborador_id, data);
CREATE INDEX IF NOT EXISTS idx_dp_colaboradores_company_ativo ON public.dp_colaboradores (company_id, ativo);
CREATE INDEX IF NOT EXISTS idx_categories_company_active ON public.categories (company_id, is_active) WHERE company_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_dp_convocacoes_colab_data ON public.dp_convocacoes (colaborador_id, data);
CREATE INDEX IF NOT EXISTS idx_dp_folgas_colab_data ON public.dp_folgas (colaborador_id, data);
CREATE INDEX IF NOT EXISTS idx_dp_documentos_company_colab ON public.dp_documentos (company_id, colaborador_id);
CREATE INDEX IF NOT EXISTS idx_dp_notificacoes_user_lida ON public.dp_notificacoes (user_id, lida_em);
CREATE INDEX IF NOT EXISTS idx_pluggy_staging_company_status ON public.pluggy_staging_transactions (company_id, status);
