INSERT INTO public.chart_account_templates (code, parent_code, name, sort_order, is_synthetic, is_tax, ai_description)
VALUES
  ('4.7','4','Receitas Complementares e de Serviços',470,false,false,'Couvert artístico, taxa de rolha, cursos, experiências e assinaturas.'),
  ('4.8','4','Receita de Locação de Espaço',480,false,false,'Aluguel do espaço para eventos e terceiros.'),
  ('4.9','4','Verbas Comerciais de Fornecedores',490,false,false,'Verbas de publicidade, exclusividade e exposição de marca.'),
  ('5.6','5','CMV de Alimentos',560,false,false,'Insumos alimentícios consumidos na produção.'),
  ('5.7','5','CMV de Bebidas',570,false,false,'Bebidas revendidas e insumos de bar.'),
  ('5.8','5','Embalagens e Materiais Diretos',580,false,false,'Embalagens, descartáveis e materiais aplicados na venda.'),
  ('5.9','5','Mão de Obra Direta Operacional',590,false,false,'Salários, encargos e benefícios da equipe de produção, salão e delivery.'),
  ('5.10','5','Perdas e Quebras de Estoque',600,false,false,'Perdas por validade, desperdício, quebras, consumo interno e inventário.'),
  ('6.1.11','6.1','IPTU',611,false,false,'Imposto predial do imóvel utilizado pela operação.'),
  ('6.1.12','6.1','Seguros',612,false,false,'Seguros patrimoniais e de responsabilidade civil.'),
  ('6.1.13','6.1','Manutenção e Conservação',613,false,false,'Manutenção predial, de cozinha, refrigeração e climatização.'),
  ('6.1.14','6.1','Limpeza e Higienização',614,false,false,'Produtos e serviços de limpeza, dedetização e lavanderia.'),
  ('6.1.15','6.1','Segurança e Monitoramento',615,false,false,'Vigilância, alarme e monitoramento.'),
  ('6.1.16','6.1','Gás',616,false,false,'Gás GLP ou encanado usado na cozinha.'),
  ('6.1.17','6.1','ECAD e Direitos Autorais',617,false,false,'Direitos autorais de música ambiente e apresentações.'),
  ('6.1.18','6.1','Coleta de Resíduos',618,false,false,'Coleta de resíduos, óleo usado e lixo comercial.'),
  ('6.1.19','6.1','Certificados Digitais e Cartórios',619,false,false,'Certificado digital, autenticações e registros.'),
  ('6.1.20','6.1','Associações e Mensalidades',620,false,false,'Sindicatos, associações e entidades de classe.'),
  ('6.1.21','6.1','Correios e Fretes Administrativos',621,false,false,'Postagens e fretes que não são de venda.'),
  ('6.1.22','6.1','Auditoria',622,false,false,'Serviços de auditoria interna ou externa.'),
  ('6.3.7','6.3','Recrutamento e Seleção',637,false,false,'Anúncios de vaga, agências e exames admissionais de contratação.'),
  ('6.3.8','6.3','Saúde e Segurança Ocupacional',638,false,false,'PCMSO, PGR, exames periódicos e SESMT.'),
  ('6.3.9','6.3','Uniformes e EPIs',639,false,false,'Uniformes, calçados e equipamentos de proteção.'),
  ('6.5','6','Despesas Variáveis de Venda',650,true,false,'Gastos que variam diretamente com a venda e compõem a margem de contribuição.'),
  ('6.5.1','6.5','Comissões de Marketplaces',651,false,false,'Comissão dos aplicativos de pedido e marketplaces.'),
  ('6.5.2','6.5','Fretes e Entregas',652,false,false,'Frete de marketplaces, entregas contratadas e subsídio de frete.'),
  ('6.5.3','6.5','Cupons, Cashback e Fidelidade',653,false,false,'Descontos promocionais financiados pela empresa.'),
  ('6.5.4','6.5','Taxas de Meios de Pagamento',654,false,false,'Taxas de cartão, vales, gateways e aluguel de máquinas.'),
  ('6.5.5','6.5','Chargebacks e Contestações',655,false,false,'Vendas contestadas e perdidas.'),
  ('7.6','7','Antecipação de Recebíveis',760,false,false,'Custo da antecipação de vendas e recebíveis.'),
  ('7.7','7','Tarifas de Boletos',770,false,false,'Emissão, liquidação e baixa de boletos.'),
  ('7.8','7','Variações e Diferenças de Conciliação',780,false,false,'Ajustes negativos de conciliação e variações financeiras.'),
  ('8.7','8','Impostos Retidos',870,false,true,'Tributos retidos na fonte de terceiros ou pelo tomador.'),
  ('8.8','8','Outros Tributos',880,false,true,'Demais tributos não classificados nas contas anteriores.')
ON CONFLICT (code) DO UPDATE
  SET parent_code = EXCLUDED.parent_code,
      name = EXCLUDED.name,
      sort_order = EXCLUDED.sort_order,
      is_synthetic = EXCLUDED.is_synthetic,
      is_tax = EXCLUDED.is_tax,
      ai_description = EXCLUDED.ai_description;